# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'XFGamingStore.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    StoreAsTar: true
- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'xama'
    appSlug: 'Organization-Romulo/XamarinDroid'
    appFile: '/Users/runner/work/1/b/Release/com.companyname.xfgamingstore.apk'
    buildVersion: '1'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'teste build'
    destinationType: 'groups'
    distributionGroupId: '41df8291-152e-419b-a790-59a30bd03ffb'
